server:
  servlet:
    context-path: /enterprise
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"

spring:
  security:
    cors:
      allowed:
        origins: ${CORS_ALLOWED_ORIGINS}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  application:
    name: enterprise
    homepage: http://localhost:4200 # TODO: hard code?
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    output-query-results: false
    create-schemas: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: true
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: latest
      group-id: sep490-enterprise

logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
        security: WARN
      hibernate: WARN
    greenbuildings: DEBUG

payment:
  payos:
    client_id: ${PAYOS_CLIENT_ID}
    api_key: ${PAYOS_API_KEY}
    checksum_key: ${PAYOS_CHECKSUM_KEY}
    returnPath: /enterprise/payment
    cancelPath: /enterprise/payment

exchangerate-api:
  key: ${EXCHANGERATE_API_KEY}
  url: https://v6.exchangerate-api.com/v6/

geocoding:
  key: ${GEOCODING_API_KEY}
  url: https://geocode.maps.co/reverse